### PR TITLE
HTML Fixes: package flavors and invalid message ID

### LINKED ISSUE #193: commit caching
At least on the AWS instance, the 'Commit found by commit id' banner disappears if the commit is cached.

To reproduce:

`[root@nginx01 /]# rm -rf ~freshports/cache/commits/*
`
Then view commit.php?category=devel&port=jenkins&files=yes&message_id=202101202217.10KMHDK1008370@repo.freebsd.org

### LINKED ISSUE #204: commit.php with files=yes and message_id not found renders HTML poorly
If the message_id is not found usually because the commit has not yet been processed, but also because of vuln testing by researchers, the HTML is lacking something.

This is on both `master` and `subversion-only` branches.

EDIT: this screen shot is not related.

Screen Shot 2021-01-26 at 2 16 41 PM

### PR DESCRIPTION
**Pull request by jethron**
- Fixes some validation errors introduced in the fix for #287
- Improve HTML semantics in pkg install instructions (kbd over code elements)
- Fixes commit.php page rendering when given an invalid `message_id`  (fixes #204) (also should fix #193 when combined with #292)
- Clean up old announcement handling

### CODE REVIEW

File: www/commit.php [hunk 1]
```diff
@@ -134,31 +134,19 @@
...
 
-	<?php echo freshports_MainTable(); ?>
+	echo freshports_MainTable(); ?>
 
 	<tr><td class="content">
 
-	<?php echo freshports_MainContentTable(BORDER); ?>
-
-<?
-	if (file_exists("announcement.txt") && filesize("announcement.txt") > 4) {
```
Comment (dlangille) [inline www/commit.php:153]: Sad to see this go. It's been around so long...

**Comment by dlangille** [comment]
Now in prod.
